import{a as v,i as a,S as P}from"./assets/vendor-DFCQGEf1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function m(r,o){const s="50194034-6daf74b2774d983dcc54e4495",n="https://pixabay.com/api/",t={key:s,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15};try{return(await v.get(n,{params:t})).data}catch{return a.error({title:"Error",message:"Illegal operation"}),[]}}const f=document.querySelector(".loader"),y=document.querySelector(".gallery"),q=new P(".gallery a",{captionsData:"alt",captionDelay:250}),c=document.querySelector(".load-more");function p(r){const o=r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:t,views:i,comments:E,downloads:S})=>`<li class="gallery-item">
        <a class="gallery-link" href="${n}">
        <img class="img-item" src="${s}" alt="${e}"/>
        </a>
        <p>Likes <span>${t}</span></p>
        <p>View <span>${i}</span></p>
        <p>Comments <span>${E}</span></p>
        <p>Downloads <span>${S}</span></p>
        </li>`).join("");y.insertAdjacentHTML("beforeend",o),q.refresh()}function w(){y.innerHTML=""}function g(){f.classList.add("is-visible")}function h(){f.classList.remove("is-visible")}function L(){c&&(c.classList.add("is-visible"),c.style.display="block")}function u(){c&&(c.classList.remove("is-visible"),c.style.display="none")}function M(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}document.querySelector(".gallery");const A=document.querySelector(".form");document.querySelector('[type="submit"]');const B=document.querySelector('[name="search-text"]');document.querySelector(".loader");const $=document.querySelector(".load-more");let d="",l=1;const b=15;u();A.addEventListener("submit",async function(r){r.preventDefault();const o=B.value.trim();if(o===""){a.warning({title:"Caution",message:"You forgot important data"});return}d=o,l=1,g(),w(),u();try{const s=await m(d,l);if(s.hits.length===0){a.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(s.hits),l++;const n=Math.ceil(s.totalHits/b);l>=n?(u(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):L()}catch(s){console.log("Error: ",s),a.error({title:"Error",message:"Error fetching images."})}finally{h()}});$.addEventListener("click",async()=>{g(),u();try{const r=await m(d,l);if(r.hits.length===0){a.info({title:"Info",message:"No more images to load."});return}p(r.hits),l++,M();const o=Math.ceil(r.totalHits/b);l>=o?(u(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):L()}catch(r){console.error("Error: ",r),a.error({title:"Error",message:"Could not load more images"})}finally{h()}});
//# sourceMappingURL=index.js.map
